name: Pull Request
run-name: Pull Request
on: [pull_request]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test --workspace fire-client
      - run: bun run --cwd packages/fire-client fmt-check
      - run: bun run --cwd packages/fire-client lint
      - run: bun run --cwd packages/fire-client tsc
      - run: bun run --cwd packages/fire-client build-storybook
